"""
ltpwr_to_touchstone.py
======================
Convert LTpowerAnalyzer measured source-impedance export to Touchstone format
using scikit-rf for import into Ansys SIwave
(PI-AC Analysis → Decoupling Optimization → DC/DC converter output impedance).

Input:  sim/Measured_source_impedance.txt
        Columns (tab-separated, comma decimal separator):
          run_id | freq_Hz | Z_mag_Ohm | Z_phase_deg
        Multiple runs may be present; the script selects the run with the
        widest frequency range by default.

Outputs (both written):
  sim/Measured_source_impedance.z1p   — Touchstone Z-parameter 1-port (best accuracy)
  sim/Measured_source_impedance.s1p   — Touchstone S-parameter 1-port (Z0=50 Ω, fallback)

SIwave import:
  Use the .z1p file: File → Import → Touchstone → select .z1p
  In Decoupling Optimization, assign as DC/DC converter output impedance.

Usage:
    python sim/ltpwr_to_touchstone.py
    python sim/ltpwr_to_touchstone.py --input  sim/Measured_source_impedance.txt
                                      --run 2
                                      --plot
    pip install scikit-rf numpy matplotlib
"""

import argparse
import re
import sys
from pathlib import Path

import numpy as np

try:
    import skrf as rf
except ImportError:
    sys.exit("scikit-rf is required: pip install scikit-rf")


# ─── parse ────────────────────────────────────────────────────────────────────

def _fix_decimal(s: str) -> str:
    return s.replace(",", ".")


def load_ltpwr(path: Path) -> dict[int, list[tuple[float, float, float]]]:
    """
    Return {run_id: [(freq_Hz, Z_mag_Ohm, Z_phase_deg), ...]}.
    Lines starting with '#' and header lines are skipped.
    """
    runs: dict[int, list[tuple[float, float, float]]] = {}
    with path.open(encoding="utf-8-sig") as fh:
        for raw in fh:
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            parts = re.split(r"\t+|\s{2,}", line)
            if len(parts) < 4:
                continue
            try:
                run   = int(parts[0])
                freq  = float(_fix_decimal(parts[1]))
                z_mag = float(_fix_decimal(parts[2]))
                phase = float(_fix_decimal(parts[3]))
            except ValueError:
                continue
            runs.setdefault(run, []).append((freq, z_mag, phase))
    return runs


def select_run(runs: dict[int, list], requested: int | None) -> list[tuple[float, float, float]]:
    if requested is not None:
        if requested not in runs:
            sys.exit(f"Run {requested} not found; available: {sorted(runs)}")
        return sorted(runs[requested])
    best = max(runs.values(), key=lambda pts: pts[-1][0] / pts[0][0] if pts else 0)
    return sorted(best)


# ─── build scikit-rf Network ──────────────────────────────────────────────────

def build_network(points: list[tuple[float, float, float]]) -> "rf.Network":
    """
    Build a 1-port scikit-rf Network from (freq, |Z|, phase_deg) data.
    The network is defined directly from Z-parameters to preserve full precision.
    """
    freqs   = np.array([p[0] for p in points])
    z_mag   = np.array([p[1] for p in points])
    z_phase = np.deg2rad(np.array([p[2] for p in points]))

    # Complex impedance (n_freq, 1, 1)
    Z_complex = (z_mag * np.exp(1j * z_phase)).reshape(-1, 1, 1)

    freq_obj = rf.Frequency.from_f(freqs, unit="hz")
    ntwk = rf.Network(frequency=freq_obj)
    ntwk.z0 = np.ones((len(freqs), 1)) * 50.0   # reference impedance (required by skrf)
    ntwk.z = Z_complex          # set Z-parameters directly
    return ntwk


# ─── write files ─────────────────────────────────────────────────────────────

def write_z1p(ntwk: "rf.Network", path: Path) -> None:
    """
    Write a Touchstone Z-parameter 1-port file (*.z1p).
    Format: # Hz Z RI R 1
    Data: freq  Re(Z11_Ohm)  Im(Z11_Ohm)
    Writing Z directly avoids the 50 Ω S-parameter conversion and preserves
    full phase accuracy for low-impedance PDN sources.
    """
    lines = [
        "! Source: LTpowerAnalyzer measured DC/DC converter output impedance\n",
        "! Generated by ltpwr_to_touchstone.py (scikit-rf)\n",
        "! Z11 written directly in Ohms — use this file in SIwave for best accuracy\n",
        "# Hz Z RI R 1\n",
    ]
    z11 = ntwk.z[:, 0, 0]   # complex Z in Ohms
    for f, z in zip(ntwk.f, z11):
        lines.append(f"{f:.6e}  {z.real:+.9e}  {z.imag:+.9e}\n")
    path.write_text("".join(lines), encoding="utf-8")
    print(f"  Wrote Z1P  → {path}")


def write_outputs(ntwk: "rf.Network", src: Path) -> tuple[Path, Path]:
    """Write Z-parameter (.z1p) and S-parameter (.s1p) Touchstone files."""
    z1p_path = src.with_suffix(".z1p")
    s1p_path = src.with_suffix(".s1p")

    # Z-parameter Touchstone — direct Z, no 50 Ω conversion, full phase accuracy
    write_z1p(ntwk, z1p_path)

    # S-parameter Touchstone — standard 50 Ω reference (skrf MA format)
    ntwk.write_touchstone(str(s1p_path), form="ri")
    print(f"  Wrote S1P  → {s1p_path}")

    return z1p_path, s1p_path


# ─── validation: round-trip check ────────────────────────────────────────────

def check_roundtrip(points: list[tuple[float, float, float]],
                    ntwk: "rf.Network") -> None:
    """Compare original Z vs recovered Z from the Network to verify accuracy."""
    z_orig = np.array([p[1] * np.exp(1j * np.deg2rad(p[2])) for p in points])
    z_recovered = ntwk.z[:, 0, 0]

    mag_err_pct = np.abs(np.abs(z_recovered) - np.abs(z_orig)) / np.abs(z_orig) * 100
    phase_err   = np.abs(np.angle(z_recovered, deg=True) - np.angle(z_orig, deg=True))

    print(f"  Round-trip check (Network Z vs original):")
    print(f"    |Z| max error : {mag_err_pct.max():.4f} %")
    print(f"    Phase max err : {phase_err.max():.6f} °")


# ─── optional plot ─────────────────────────────────────────────────────────────

def plot_network(ntwk: "rf.Network", src: Path) -> None:
    try:
        import matplotlib.pyplot as plt
    except ImportError:
        print("matplotlib not installed — skipping plot")
        return

    freqs = ntwk.f
    z     = ntwk.z[:, 0, 0]

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(9, 6), sharex=True)

    ax1.loglog(freqs, np.abs(z) * 1e3, color="steelblue")
    ax1.set_ylabel("|Z| (mΩ)")
    ax1.set_title(f"DC/DC Output Impedance — {src.stem}")
    ax1.grid(True, which="both", ls="--", alpha=0.5)

    ax2.semilogx(freqs, np.angle(z, deg=True), color="darkorange")
    ax2.set_ylabel("Phase (°)")
    ax2.set_xlabel("Frequency (Hz)")
    ax2.axhline(0, color="gray", lw=0.7)
    ax2.grid(True, which="both", ls="--", alpha=0.5)

    plt.tight_layout()
    out_png = src.with_name(src.stem + "_impedance.png")
    plt.savefig(out_png, dpi=150)
    print(f"  Plot saved → {out_png}")
    plt.show()


# ─── main ─────────────────────────────────────────────────────────────────────

def main() -> None:
    ap = argparse.ArgumentParser(
        description="LTpowerAnalyzer Z(f) → Touchstone S1P/Z1P via scikit-rf")
    ap.add_argument("--input",  default="sim/Measured_source_impedance.txt",
                    help="LTpowerAnalyzer export file (default: %(default)s)")
    ap.add_argument("--run",    type=int, default=None,
                    help="Run number to use (default: widest frequency range)")
    ap.add_argument("--plot",   action="store_true",
                    help="Show |Z|(f) and phase(f) plot")
    args = ap.parse_args()

    src = Path(args.input)
    if not src.exists():
        sys.exit(f"Input file not found: {src}")

    runs = load_ltpwr(src)
    if not runs:
        sys.exit("No data rows parsed — check file format")

    print(f"Runs found : {sorted(runs)}  "
          f"(points: {[len(v) for v in runs.values()]})")
    points = select_run(runs, args.run)
    print(f"Using run  : {args.run or '(widest)'}  "
          f"{points[0][0]:.1f} Hz – {points[-1][0]:.1f} Hz  "
          f"({len(points)} points)\n")

    ntwk = build_network(points)
    check_roundtrip(points, ntwk)

    z1p, s1p = write_outputs(ntwk, src)
    print(f"\n  Written: {z1p}  ← use this in SIwave (full phase accuracy)")
    print(f"  Written: {s1p}  ← S-parameter fallback (Z0=50 Ω)")

    # Spot-check table
    print("\nImpedance spot checks:")
    print(f"  {'Freq':>12}  {'|Z| (mΩ)':>12}  {'Phase (°)':>10}")
    for target in [100, 1e3, 10e3, 100e3, 1e6, 10e6]:
        closest = min(points, key=lambda p: abs(p[0] - target))
        print(f"  {closest[0]:>12.0f}  {closest[1]*1e3:>12.4f}  {closest[2]:>10.2f}")

    if args.plot:
        plot_network(ntwk, src)


if __name__ == "__main__":
    main()
